export function getEls(){
  return {
    dashboardPage: document.getElementById("dashboardPage"),
    novoAtendimentoPage: document.getElementById("novoAtendimentoPage"),

    subtitle: document.getElementById("subtitle"),
    mesSelect: document.getElementById("mesSelect"),
    anoSelect: document.getElementById("anoSelect"),
    jsonFile: document.getElementById("jsonFile"),
    fileName: document.getElementById("fileName"),
    idLocalidadeSearch: document.getElementById("idLocalidadeSearch"),
    ticketSearch: document.getElementById("ticketSearch"),
    btnClearSearch: document.getElementById("btnClearSearch"),
    btnExportPPTX: document.getElementById("btnExportPPTX"),
    btnExportPDF: document.getElementById("btnExportPDF"),
    btnAcoes: document.getElementById("btnAcoes"),
    errorBox: document.getElementById("errorBox"),
    kpiTickets: document.getElementById("kpiTickets"),
    kpiTicketsSub: document.getElementById("kpiTicketsSub"),
    kpiLocais: document.getElementById("kpiLocais"),
    kpiEquip: document.getElementById("kpiEquip"),
    kpiEquipSub: document.getElementById("kpiEquipSub"),
    kpiEquipCfg: document.getElementById("kpiEquipCfg"),
    kpiEquipCfgSub: document.getElementById("kpiEquipCfgSub"),
    kpiTempoHoras: document.getElementById("kpiTempoHoras"),
    kpiTempoHorasSub: document.getElementById("kpiTempoHorasSub"),
    kpiMediaPontos: document.getElementById("kpiMediaPontos"),
    kpiMediaPontosSub: document.getElementById("kpiMediaPontosSub"),
    tbody: document.getElementById("tbodyLocais"),
    totalFiltro: document.getElementById("totalFiltro"),
    cvTempo: document.getElementById("chartTempo"),
    cvTickets: document.getElementById("chartTickets"),
    cvEquip: document.getElementById("chartEquip"),
    selectedInfo: document.getElementById("selectedInfo"),
    galleryHint: document.getElementById("galleryHint"),
    beforeBox: document.getElementById("beforeBox"),
    afterBox: document.getElementById("afterBox"),
    beforeImg: document.getElementById("beforeImg"),
    afterImg: document.getElementById("afterImg"),
    beforeMeta: document.getElementById("beforeMeta"),
    afterMeta: document.getElementById("afterMeta"),
    beforeLink: document.getElementById("beforeLink"),
    afterLink: document.getElementById("afterLink"),
    descAtendimento: document.getElementById("descAtendimento"),

    yssyLogo: document.getElementById("yssyLogo"),
    yssyFallback: document.getElementById("yssyFallback"),

    btnVoltarDashboard: document.getElementById("btnVoltarDashboard"),
    btnAtualizarLista: document.getElementById("btnAtualizarLista"),
    btnTestarConexao: document.getElementById("btnTestarConexao"),
    btnLimparFormulario: document.getElementById("btnLimparFormulario"),
    btnLimparFiltrosTabela: document.getElementById("btnLimparFiltrosTabela"),

    formAcao: document.getElementById("formAcao"),
    api_base: document.getElementById("api_base"),
    statusApi: document.getElementById("statusApi"),
    statusForm: document.getElementById("statusForm"),
    statusTabela: document.getElementById("statusTabela"),
    tbodyAcoes: document.getElementById("tbody_acoes"),
    filtroBusca: document.getElementById("filtroBusca"),
    filtroAno: document.getElementById("filtroAno"),
    filtroMes: document.getElementById("filtroMes"),

    ano: document.getElementById("ano"),
    mes: document.getElementById("mes"),
    dia: document.getElementById("dia"),
    numero_ticket: document.getElementById("numero_ticket"),
    id_localidade: document.getElementById("id_localidade"),
    localidade: document.getElementById("localidade"),
    tempo_gasto_horas: document.getElementById("tempo_gasto_horas"),
    equipamentos_trocados: document.getElementById("equipamentos_trocados"),
    equipamentos_configurados: document.getElementById("equipamentos_configurados"),
    pontos_de_rede: document.getElementById("pontos_de_rede"),
    foto_antes_url: document.getElementById("foto_antes_url"),
    foto_depois_url: document.getElementById("foto_depois_url"),
    descricao_atendimento: document.getElementById("descricao_atendimento"),
  };
}